#include "cpu.h"

CPU::CPU() : m_PC{0x100} { }

void CPU::ExecuteNextInstruction()
{
    uint8_t opcode;

}

void CPU::InitCommands()
{
    m_commands[0x00] = [](){};
    m_commands[0x01] = [](){};
    m_commands[0x02] = [](){};
    m_commands[0x03] = [](){};
    m_commands[0x04] = [](){};
    m_commands[0x05] = [](){};
    m_commands[0x06] = [](){};
    m_commands[0x07] = [](){};
    m_commands[0x08] = [](){};
    m_commands[0x09] = [](){};
    m_commands[0x0A] = [](){};
    m_commands[0x0B] = [](){};
    m_commands[0x0C] = [](){};
    m_commands[0x0D] = [](){};
    m_commands[0x0E] = [](){};
    m_commands[0x0F] = [](){};

    m_commands[0x10] = [](){};
    m_commands[0x11] = [](){};
    m_commands[0x12] = [](){};
    m_commands[0x13] = [](){};
    m_commands[0x14] = [](){};
    m_commands[0x15] = [](){};
    m_commands[0x16] = [](){};
    m_commands[0x17] = [](){};
    m_commands[0x18] = [](){};
    m_commands[0x19] = [](){};
    m_commands[0x1A] = [](){};
    m_commands[0x1B] = [](){};
    m_commands[0x1C] = [](){};
    m_commands[0x1D] = [](){};
    m_commands[0x1E] = [](){};
    m_commands[0x1F] = [](){};

    m_commands[0x20] = [](){};
    m_commands[0x21] = [](){};
    m_commands[0x22] = [](){};
    m_commands[0x23] = [](){};
    m_commands[0x24] = [](){};
    m_commands[0x25] = [](){};
    m_commands[0x26] = [](){};
    m_commands[0x27] = [](){};
    m_commands[0x28] = [](){};
    m_commands[0x29] = [](){};
    m_commands[0x2A] = [](){};
    m_commands[0x2B] = [](){};
    m_commands[0x2C] = [](){};
    m_commands[0x2D] = [](){};
    m_commands[0x2E] = [](){};
    m_commands[0x2F] = [](){};

    m_commands[0x30] = [](){};
    m_commands[0x31] = [](){};
    m_commands[0x32] = [](){};
    m_commands[0x33] = [](){};
    m_commands[0x34] = [](){};
    m_commands[0x35] = [](){};
    m_commands[0x36] = [](){};
    m_commands[0x37] = [](){};
    m_commands[0x38] = [](){};
    m_commands[0x39] = [](){};
    m_commands[0x3A] = [](){};
    m_commands[0x3B] = [](){};
    m_commands[0x3C] = [](){};
    m_commands[0x3D] = [](){};
    m_commands[0x3E] = [](){};
    m_commands[0x3F] = [](){};

    m_commands[0x40] = [](){};
    m_commands[0x41] = [](){};
    m_commands[0x42] = [](){};
    m_commands[0x43] = [](){};
    m_commands[0x44] = [](){};
    m_commands[0x45] = [](){};
    m_commands[0x46] = [](){};
    m_commands[0x47] = [](){};
    m_commands[0x48] = [](){};
    m_commands[0x49] = [](){};
    m_commands[0x4A] = [](){};
    m_commands[0x4B] = [](){};
    m_commands[0x4C] = [](){};
    m_commands[0x4D] = [](){};
    m_commands[0x4E] = [](){};
    m_commands[0x4F] = [](){};

    m_commands[0x50] = [](){};
    m_commands[0x51] = [](){};
    m_commands[0x52] = [](){};
    m_commands[0x53] = [](){};
    m_commands[0x54] = [](){};
    m_commands[0x55] = [](){};
    m_commands[0x56] = [](){};
    m_commands[0x57] = [](){};
    m_commands[0x58] = [](){};
    m_commands[0x59] = [](){};
    m_commands[0x5A] = [](){};
    m_commands[0x5B] = [](){};
    m_commands[0x5C] = [](){};
    m_commands[0x5D] = [](){};
    m_commands[0x5E] = [](){};
    m_commands[0x5F] = [](){};

    m_commands[0x60] = [](){};
    m_commands[0x61] = [](){};
    m_commands[0x62] = [](){};
    m_commands[0x63] = [](){};
    m_commands[0x64] = [](){};
    m_commands[0x65] = [](){};
    m_commands[0x66] = [](){};
    m_commands[0x67] = [](){};
    m_commands[0x68] = [](){};
    m_commands[0x69] = [](){};
    m_commands[0x6A] = [](){};
    m_commands[0x6B] = [](){};
    m_commands[0x6C] = [](){};
    m_commands[0x6D] = [](){};
    m_commands[0x6E] = [](){};
    m_commands[0x6F] = [](){};

    m_commands[0x70] = [](){};
    m_commands[0x71] = [](){};
    m_commands[0x72] = [](){};
    m_commands[0x73] = [](){};
    m_commands[0x74] = [](){};
    m_commands[0x75] = [](){};
    m_commands[0x76] = [](){};
    m_commands[0x77] = [](){};
    m_commands[0x78] = [](){};
    m_commands[0x79] = [](){};
    m_commands[0x7A] = [](){};
    m_commands[0x7B] = [](){};
    m_commands[0x7C] = [](){};
    m_commands[0x7D] = [](){};
    m_commands[0x7E] = [](){};
    m_commands[0x7F] = [](){};
    
    m_commands[0x80] = [](){};
    m_commands[0x81] = [](){};
    m_commands[0x82] = [](){};
    m_commands[0x83] = [](){};
    m_commands[0x84] = [](){};
    m_commands[0x85] = [](){};
    m_commands[0x86] = [](){};
    m_commands[0x87] = [](){};
    m_commands[0x88] = [](){};
    m_commands[0x89] = [](){};
    m_commands[0x8A] = [](){};
    m_commands[0x8B] = [](){};
    m_commands[0x8C] = [](){};
    m_commands[0x8D] = [](){};
    m_commands[0x8E] = [](){};
    m_commands[0x8F] = [](){};
    
    m_commands[0x90] = [](){};
    m_commands[0x91] = [](){};
    m_commands[0x92] = [](){};
    m_commands[0x93] = [](){};
    m_commands[0x94] = [](){};
    m_commands[0x95] = [](){};
    m_commands[0x96] = [](){};
    m_commands[0x97] = [](){};
    m_commands[0x98] = [](){};
    m_commands[0x99] = [](){};
    m_commands[0x9A] = [](){};
    m_commands[0x9B] = [](){};
    m_commands[0x9C] = [](){};
    m_commands[0x9D] = [](){};
    m_commands[0x9E] = [](){};
    m_commands[0x9F] = [](){};

    m_commands[0xA0] = [](){};
    m_commands[0xA1] = [](){};
    m_commands[0xA2] = [](){};
    m_commands[0xA3] = [](){};
    m_commands[0xA4] = [](){};
    m_commands[0xA5] = [](){};
    m_commands[0xA6] = [](){};
    m_commands[0xA7] = [](){};
    m_commands[0xA8] = [](){};
    m_commands[0xA9] = [](){};
    m_commands[0xAA] = [](){};
    m_commands[0xAB] = [](){};
    m_commands[0xAC] = [](){};
    m_commands[0xAD] = [](){};
    m_commands[0xAE] = [](){};
    m_commands[0xAF] = [](){};

    m_commands[0xB0] = [](){};
    m_commands[0xB1] = [](){};
    m_commands[0xB2] = [](){};
    m_commands[0xB3] = [](){};
    m_commands[0xB4] = [](){};
    m_commands[0xB5] = [](){};
    m_commands[0xB6] = [](){};
    m_commands[0xB7] = [](){};
    m_commands[0xB8] = [](){};
    m_commands[0xB9] = [](){};
    m_commands[0xBA] = [](){};
    m_commands[0xBB] = [](){};
    m_commands[0xBC] = [](){};
    m_commands[0xBD] = [](){};
    m_commands[0xBE] = [](){};
    m_commands[0xBF] = [](){};

    m_commands[0xC0] = [](){};
    m_commands[0xC1] = [](){};
    m_commands[0xC2] = [](){};
    m_commands[0xC3] = [](){};
    m_commands[0xC4] = [](){};
    m_commands[0xC5] = [](){};
    m_commands[0xC6] = [](){};
    m_commands[0xC7] = [](){};
    m_commands[0xC8] = [](){};
    m_commands[0xC9] = [](){};
    m_commands[0xCA] = [](){};
    m_commands[0xCB] = [](){};
    m_commands[0xCC] = [](){};
    m_commands[0xCD] = [](){};
    m_commands[0xCE] = [](){};
    m_commands[0xCF] = [](){};

    m_commands[0xD0] = [](){};
    m_commands[0xD1] = [](){};
    m_commands[0xD2] = [](){};
    m_commands[0xD3] = [](){};
    m_commands[0xD4] = [](){};
    m_commands[0xD5] = [](){};
    m_commands[0xD6] = [](){};
    m_commands[0xD7] = [](){};
    m_commands[0xD8] = [](){};
    m_commands[0xD9] = [](){};
    m_commands[0xDA] = [](){};
    m_commands[0xDB] = [](){};
    m_commands[0xDC] = [](){};
    m_commands[0xDD] = [](){};
    m_commands[0xDE] = [](){};
    m_commands[0xDF] = [](){};

    m_commands[0xE0] = [](){};
    m_commands[0xE1] = [](){};
    m_commands[0xE2] = [](){};
    m_commands[0xE3] = [](){};
    m_commands[0xE4] = [](){};
    m_commands[0xE5] = [](){};
    m_commands[0xE6] = [](){};
    m_commands[0xE7] = [](){};
    m_commands[0xE8] = [](){};
    m_commands[0xE9] = [](){};
    m_commands[0xEA] = [](){};
    m_commands[0xEB] = [](){};
    m_commands[0xEC] = [](){};
    m_commands[0xED] = [](){};
    m_commands[0xEE] = [](){};
    m_commands[0xEF] = [](){};

    m_commands[0xF0] = [](){};
    m_commands[0xF1] = [](){};
    m_commands[0xF2] = [](){};
    m_commands[0xF3] = [](){};
    m_commands[0xF4] = [](){};
    m_commands[0xF5] = [](){};
    m_commands[0xF6] = [](){};
    m_commands[0xF7] = [](){};
    m_commands[0xF8] = [](){};
    m_commands[0xF9] = [](){};
    m_commands[0xFA] = [](){};
    m_commands[0xFB] = [](){};
    m_commands[0xFC] = [](){};
    m_commands[0xFD] = [](){};
    m_commands[0xFE] = [](){};
    m_commands[0xFF] = [](){};
}
